version: '3.6'

services:
  proxy:
    image: nginx:1.21-alpine
    ports:
      - "8800:80"
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
  backend:
    image: django-template:development
    volumes:
      - ./backend:/home/python/app
  frontend:
    image: nuxt-template:development
    volumes:
      - ./frontend:/home/nuxt/app

volumes:
  postgres_data:
