[tool.pylint.format]
max-line-length = 88

[tool.vulture]
exclude = ["migrations/"]
min_confidence = 100

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''

[tool.isort]
multi_line_output = 3
force_grid_wrap = 0
use_parentheses = true
line_length = 88
skip = "migrations"
default_section = "THIRDPARTY"
known_first_party = []
known_django = "django"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "DJANGO", "FIRSTPARTY", "LOCALFOLDER"]
combine_as_imports = true
include_trailing_comma = true

[tool.pytest.ini_options]
addopts = "./backend --nomigrations --disable-pytest-warnings --disable-warnings --ds=config.settings.tests"
